name: Audit pull request
on: pull_request

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: 'Wait for deploy preview to finish'
    uses: 'WyriHaximus/github-action-wait-for-status@master'
    with:
        # We care only about the Netlify checks finishing
        ignoreActions: 'lighthouse audit,triage,notify,tests'
        checkInterval: 20
    env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - name: Audit Netlify deploy preview
        uses: jakejarvis/lighthouse-action@master
        with:
          netlify_site: "amazing-fermat-84779e.netlify.com"
      - uses: actions/upload-artifact@master
        with:
          name: report
          path: "./report"
